# Team-specific severity remapping
# Phase 3 Session 7: Severity Remapping

# Remap rule severities for team context
# User-facing: MUST/SHOULD/MAY
# Internal: error/warn/note

severity_remaps:
  # Example: Lower TypeScript strict enforcement during migration
  - rule_id: typescript/strict-mode
    from: MUST
    to: warn # Maps to internal 'warn' level
    rationale_file: RATIONALE.md

  # Example: Elevate documentation requirements
  - rule_id: docs/readme-required
    from: SHOULD
    to: error # Maps to internal 'error' level

# Guardrail: Lowering MUST to 'info' requires rationale_file
# with documented justification and issue link

